### ISSUE TITLE
OBSERVE: Indicators for DCF, ICCAT and IOTC reports

### ISSUE THREAD

**Issue by JulienLebranchu** [OB7-IRD/fishi#3]
The list of indicator that I need for DCF, ICCAT and IOTC reports

- [x] Total number of PSUs in the implementation year 
- [x] Achieved number of PSUs in the implementation year 
- [x] Number of unique active vessels in the sampling frame 
- [x] Number of unique vessels sampled 
- [x] Number of fishing trips in the sampling frame 
- [x] Number of fishing trips sampled 
- [x] Number of species for each biological variables (length, sex, weight, maturity)

## Specific on board sampling
- [ ] Number of Days at sea per program
- [ ] Number of fishing days per program

PSU is relative to a sampling plan:

- Actually it's a **vessel*trip**
- Previously, it has also been **vessel*well**

Database :

- Observe

**Comment by ClaraLerebourg** [comment]
New indicators (merge on development) :
- set_total : Total sets events, sampled or not, with or without tuna landings.
- psu_total : Total sets events, sampled or not, with tuna landings (variables : trip, well and vessel).
- sample_summary : Give the number of trip, vessel or well sampled for a given year 
- species_biological_variable : Give the number of each biological variable, sampled, for a given year
