### ISSUE TITLE
Add 4 logbook indicators

### ISSUE THREAD

**Issue by ClaraLerebourg** [OB7-IRD/fishi#7]
- [x] **Data_availability :** Control to verify the availability of LB, OBS and OBS data.
     - [x] Name
     - [x] Title
     - [x] description
     - [x] ggplot
     - [ ] check that the function is working properly

- [x]  **Control_trip_map :** Check the consistency between LB and OBS data (Positions, number of sets and deployments)
     - [x] Name
     - [x] Title
     - [x] description
     - [x] ggplot
     - [ ] check that the function is working properly

- [ ] **Control_trip**
     - [ ] Name
     - [ ] Title
     - [ ] description
     - [ ] check that the function is working properly

**Comment by esthermollier** [comment]
Suite à nos conversations et à la réunion d'équipe, voilà les quelques corrections que nous avons identifié ensemble:

- Utiliser le même sql pour toutes les fonctions, les modifications auront lieu directement sur R. L'objectif est d'optimiser le temps de traitement de la fonction (éviter de refaire l'extraction de données à chaque fois et notamment celle des VMS qui est très longue) 
- Préciser sur quelle branche on est en haut du quarto, ainsi que la version et la date afin d'avoir toutes les clefs en main pour faire tourner les fonctions 
- Choisir le nom de l'océan et pas le numéro 
- Enregistrer les images selon les bonnes tailles
- Optimiser la vitesse pour l'extraction des données VMS : sélection selon année
- Sql : choix des années avec marées à cheval sur deux années (start 2023 ou end 2023)

**Data availability** 
- Ecarter les couleurs : pas de superposition des croix 
- Extraire toutes les activités pas uniquement les sets, à corriger pour observe 
- Mettre en interactif ggplotly
- Possibilité de fournir une période temporelle, date de début et date de fin, qui prend l’année au milieu 

**Trip effort** 
-  Fusionner avec sample summary 

**Control trip :**
- Remplacer t3 par observe logbook
- Mettre nom : t3 deviens logbook 

**Control trip map** 
- Mettre le ggplot en plotly, sans la zee
